name: Checkout by env
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Please select the environment to use
#        default: 'dev'
#        options:
#        - dev
#        - live
        required: true
        options: ['dev', 'live', 'test']




jobs:
  get-code:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Print content
        run: |
          echo "Selected env1: ${{ github.event.inputs.environment }}"
          echo "Selected env2: ${{ inputs.environment }}"
          echo "System home: ${{ vars.SYSTEM_HOME }}"
          
      - name: Check env selection
        if: github.event.inputs.environment != 'live'
        run: |
          if [[ "${{ inputs.environment }}" == "live" ]]; then
            echo "live"
          else
            echo "no live"
          fi
  
