name: Checkout by env
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Please select the environment to use
        default: 'dev'
        options:
        - dev
        - live


jobs:
  get-code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.choice }}
    steps:
      - uses: actions/checkout@v4

      - name: Print content
        run: |
          echo "Selected env: ${{ inputs.choice }}"
          echo "System home: ${{ vars.SYSTEM_HOME }}"
          
      - name: Check env selection
        run: |
          if [[ '${{ github.environment }}' != 'live' ]]; then
            echo "Ei ole live"
          else
            echo "On live"
          fi
  
