name: Checkout by env
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Please select the environment to use
        default: 'dev'
        options:
        - dev
        - live


jobs:
  get-code:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Print content
        run: |
          echo "Selected env: ${{ github.event.inputs.environment }}"
          echo "Selected env: ${{ inputs.choice }}"
          echo "System home: ${{ vars.SYSTEM_HOME }}"
          
      #- name: Check env selection
      #  run: |
      #    if [[ "${{ github.environment }}" == "live" ]]; then
      #      echo "live"
      #    else
      #      echo "no live"
      #    fi
  
